logging:
  file:
    path: "logs"
  logback:
    rollingpolicy:
      total-size-cap: "2GB"

spring:
  output:
    ansi:
      enabled: "always"
  profiles:
    active: "prod"

discord:
  token: "Reset token from: https://discord.com/developers/applications/1324842327142957163/bot"
  application: 1324842327142957163
  guild: 1324842840278302742